[package]
name = "atcoder-problems-backend"
version = "0.1.0"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
# Logging
log = "0.4"
fern = "0.6.0"

rand = "0.7.3"
chrono = "0.4"
regex = "1"
rust-s3 = { version = "0.27.0-rc4", features = ["no-verify-ssl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# SQL
sql-client = { path = "./sql-client" }

# Scraping
atcoder-client = { path = "./atcoder-client" }

# Web framework
tide = "0.16"
cookie = "0.14"
surf = "2.3"

async-trait = "0.1"

async-std = { version = "1.9.0", features = ["attributes"] }
anyhow = "1.0.32"
tokio = { version = "1.15", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]

[workspace]
members = ["sql-client", "atcoder-client"]