name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1
  SQL_URL: postgres://db_user:db_pass@localhost:15432/test_db

jobs:
  backend_test:
    name: Run backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atcoder-problems-backend
        
    steps:
    - uses: actions/checkout@v2

    - name: Start PostgreSQL server
      run: docker-compose up -d postgresql

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git
          ~/.cargo/registry/cache
          ~/.cargo/registry/index
          ./backend/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('atcoder-problems-backend/Cargo.lock') }}

    - name: Wait for PostgreSQL
      run: |
        for i in `seq 20`
        do
          docker-compose exec -T pg_isready && break
          echo "Waiting for PostgreSQL for 3 seconds ..."
          sleep 3
        done

    - name: Setup
      run: rustup component add rustfmt

    - name: Check format
      run: cargo fmt --all -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose --workspace -- --test-threads=1
  
  frontend_test:
    name: Run frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atcoder-problems-frontend

    steps:
    - name: Setup
      run: sudo apt-get install -y libgconf-2-4
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: yarn
    - name: build
      run: yarn build
    - name: test
      run: yarn test
    - name: lint
      run: yarn lint
    - name: Integration test
      run: |
        yarn prepare-ci
        yarn start:ci &
        yarn cy:run
